### ISSUE TITLE
Figure out if we can just reuse diehard

### ISSUE THREAD

**Issue by lvh** [RackSec/banach#13]
https://github.com/sunng87/diehard/

**Comment by dm3** [comment]
I wrote https://github.com/tulos/manifail a couple weeks ago. Never saw Banach. Maybe you can use Diehard and Manifail as inspiration and come up with something even more awesome...
Otherwise, just have it on your radar :)

**Comment by lvh** [comment]
I think the recent feature PRs (and my own personal attempts at using it) have demonstrated that the strategy construction in banach is just really nice, and banach's existence is warranted, so I'm closing this.
