### ISSUE TITLE
Strategies currently can't modulate what to do next

### ISSUE THREAD

**Issue by lvh** [RackSec/banach#4]
retry currently calls `(f)` unconditionally, and strategies must synchronously return either a wait time or an exception. This is not good enough.

Here's an example case: f is a fn that gets some data from an API. That API uses a short-term auth token that you acquire with a long-term API key. Sometimes, the auth token expires and you must re-authenticate. Retry logic should be able to do this for you transparently; but that means potentially going off and doing something else (acquire a new API key), an operation which requires a deferred.

Because retry just calls `(f)`, there's no way to communicate any new information to `f` other than some shared mutable state. Shared mutable state can be OK (e.g. caching the auth token), but it'd be even nicer if we can just modulate how `f` gets called.

Suggestion:
- strategies are fns that take a map with `:failures` and `:args`, returning a maybe-deferred map of the same shape; md/recur recurs with this. Keep in mind that md/recur doesn't understand how to deal with deferreds, only md/loop's body -- so you probably have to use let-flow here.
- signature for retry becomes `[f strat]` => `[strat f & args]`, f is called as `(apply f args)`

Alternatively, we can stick to the current signature, but still have strategies return deferreds. This would mean exponentially returns a deferred that waits, instead of a number.

... _really_ what I want is Effect, where strategies return effects and f is itself an effect, but such is life.

**Comment by derwolfe** [comment]
closed by #8
